### ISSUE TITLE
How would I implement this into commands that contain Json elements?

### ISSUE THREAD

**Issue by ApplecakeYT** [Plagiatus/RCON-Action#2]
How would I implement this into commands that contain Json elements?

For Example,
```
env:
  DAY_OF_WEEK: Monday

...
commands: '["tellraw @a ["The day is ${{env.DAY_OF_WEEK}}"]"]'
```

_Originally posted by @ApplecakeYT in https://github.com/Plagiatus/RCON-Action/issues/1#issuecomment-1326888085_

**Comment by ApplecakeYT** [comment]
I figured out a way to around this by escaping the needed JSON characters with Unicode (\u005D for example).
```
["tellraw @a \u005B\"${{ github.actor }}\"\u005D"]
```
output:
`["ApplecakeYT"]`

**Comment by Plagiatus** [comment]
you can use (single) escapes inside the tellraw text:

```yml
commands: '["tellraw @a [{\"text\":\"The day is ${{env.DAY_OF_WEEK}}\"}]"]'
```
